package themis

// I-M2 (D-I-7 fixture provenance): a REAL harness walk, generated by
// this test and committed WITH provenance metadata, is the record the
// Themis repository's intake tests reconstruct. The fixture is not
// hand-authored and not "checked in" until its provenance is explicit:
//
//	real harness walk → fixture generation → committed with provenance → Themis fixture test
//
// Default mode VERIFIES the committed fixture: its constitution hash
// must equal the compiled one (a constitution change makes the fixture
// visibly stale), the record must verify, and the five production links
// must be present. THEMIS_FIXTURE_GENERATE=1 regenerates it.

import (
	"encoding/json"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"testing"
	"time"

	"github.com/tofchaliss/themis-ai-runtime/src/harness/deployment"
	"github.com/tofchaliss/themis-ai-runtime/src/harness/state"
)

const (
	fixtureCommission = "c0a8e3d6-5b1e-4f5a-9d3e-2b4c6a8e0f12"
	fixtureTask       = "fx-remediate-0001"
)

type fixtureProvenance struct {
	Generator        string `json:"generator"`
	GeneratedAt      string `json:"generated_at"`
	HarnessCommit    string `json:"harness_commit"`
	TreeDirty        bool   `json:"tree_dirty_at_generation"`
	ConstitutionHash string `json:"constitution_hash"`
	AnchorHash       string `json:"anchor_hash"`
	AnchorName       string `json:"anchor_name"`
	AnchorVersion    int    `json:"anchor_version"`
	TaskID           string `json:"task_id"`
	ArtifactBoundSeq int64  `json:"artifact_bound_seq"`
	CommissionID     string `json:"commission_id"`
	FindingID        string `json:"finding_id"`
	Skill            string `json:"skill"`
	Note             string `json:"note"`
}

func fixtureDir(t *testing.T) string {
	t.Helper()
	return filepath.Join(repoRoot(t), "evidence", "harness", "fixtures", "themis-intake", state.ConstitutionHash()[:12])
}

func copyTree(t *testing.T, src, dst string) {
	t.Helper()
	err := filepath.WalkDir(src, func(p string, d os.DirEntry, err error) error {
		if err != nil {
			return err
		}
		rel, _ := filepath.Rel(src, p)
		out := filepath.Join(dst, rel)
		if d.IsDir() {
			return os.MkdirAll(out, 0o755)
		}
		b, err := os.ReadFile(p)
		if err != nil {
			return err
		}
		return os.WriteFile(out, b, 0o644)
	})
	if err != nil {
		t.Fatal(err)
	}
}

func gitOut(t *testing.T, root string, args ...string) string {
	t.Helper()
	cmd := exec.Command(gitBin(t), args...)
	cmd.Dir = root
	out, err := cmd.Output()
	if err != nil {
		return ""
	}
	return strings.TrimSpace(string(out))
}

func TestThemisIntakeFixture(t *testing.T) {
	dir := fixtureDir(t)
	if os.Getenv("THEMIS_FIXTURE_GENERATE") == "1" {
		generateFixture(t, dir)
	}
	verifyFixture(t, dir)
}

func generateFixture(t *testing.T, dir string) {
	t.Helper()
	m := &readingParent{finding: demoFindingID}
	w, err := newWorld(t, m, worldOpts{withDoor: true, serveFinding: true}, nil)
	if err != nil {
		t.Fatal(err)
	}
	res, err := w.o.SubmitTask(w.instantiateWith(t, fixtureTask, demoFindingID, fixtureCommission))
	if err != nil || res.Status != state.StatusCompleted {
		t.Fatalf("fixture walk: %+v %v", res, err)
	}
	seq := bindingSeq(t, w, fixtureTask)
	if err := os.RemoveAll(dir); err != nil {
		t.Fatal(err)
	}
	if err := os.MkdirAll(dir, 0o755); err != nil {
		t.Fatal(err)
	}
	copyTree(t, filepath.Join(w.base, "state"), filepath.Join(dir, "state"))
	// The registries Themis's intake resolves against: the anchors
	// registry the deployment opened under, the verification contracts
	// registry with its contract bundles, and the Themis contract file.
	ab, _ := os.ReadFile(w.regs)
	_ = os.WriteFile(filepath.Join(dir, "anchors.json"), ab, 0o644)
	copyTree(t, filepath.Join(w.root, "policies", "verification"), filepath.Join(dir, "verification"))
	cb, _ := os.ReadFile(w.contract)
	_ = os.WriteFile(filepath.Join(dir, "contract.json"), cb, 0o644)
	root := repoRoot(t)
	prov := fixtureProvenance{
		Generator:        "src/themis TestThemisIntakeFixture (THEMIS_FIXTURE_GENERATE=1)",
		GeneratedAt:      time.Now().UTC().Format(time.RFC3339),
		HarnessCommit:    gitOut(t, root, "rev-parse", "HEAD"),
		TreeDirty:        gitOut(t, root, "status", "--porcelain") != "",
		ConstitutionHash: state.ConstitutionHash(),
		AnchorHash:       w.anchorSHA,
		AnchorName:       "test-rsys",
		AnchorVersion:    6,
		TaskID:           fixtureTask,
		ArtifactBoundSeq: seq,
		CommissionID:     fixtureCommission,
		FindingID:        demoFindingID,
		Skill:            "remediate-dependency@4",
		Note:             "A real remediate-dependency@4 walk under a test anchor with the HTTP read door (httptest Governance/Registry serving the demo Finding). The report was verified once (report-valid@2 PASS) and egressed unchanged. The Themis repository's intake tests reconstruct this record; they must never edit it. Regenerate whenever the L6 constitution hash moves.",
	}
	pb, _ := json.MarshalIndent(prov, "", " ")
	if err := os.WriteFile(filepath.Join(dir, "provenance.json"), append(pb, '\n'), 0o644); err != nil {
		t.Fatal(err)
	}
	t.Logf("generated fixture at %s (task %s, seq %d)", dir, fixtureTask, seq)
}

func verifyFixture(t *testing.T, dir string) {
	t.Helper()
	pb, err := os.ReadFile(filepath.Join(dir, "provenance.json"))
	if err != nil {
		t.Fatalf("no fixture for constitution %s: %v (run with THEMIS_FIXTURE_GENERATE=1)", state.ConstitutionHash()[:12], err)
	}
	var prov fixtureProvenance
	if err := json.Unmarshal(pb, &prov); err != nil {
		t.Fatal(err)
	}
	if prov.ConstitutionHash != state.ConstitutionHash() {
		t.Fatalf("fixture constitution %s ≠ compiled %s — the fixture is stale; regenerate", prov.ConstitutionHash, state.ConstitutionHash())
	}
	root, err := state.OpenRoot(filepath.Join(dir, "state"))
	if err != nil {
		t.Fatal(err)
	}
	sv, err := root.ReadStatus(prov.TaskID)
	if err != nil || sv.Status != state.StatusCompleted || sv.Verdict != state.VerdictVerified {
		t.Fatalf("fixture record: %+v %v", sv, err)
	}
	man, _ := root.ReadManifest(prov.TaskID)
	if man.ConstitutionHash != prov.ConstitutionHash || man.GovernedHashes["deployment_anchor"] != prov.AnchorHash || man.GovernedHashes["origin:commission"] != prov.CommissionID || man.GovernedHashes["skill"] != prov.Skill {
		t.Fatalf("fixture manifest disagrees with its provenance: %v", man.GovernedHashes)
	}
	// The anchor that governed the record is registered in the fixture's
	// registry, and its bytes are in the record (D-T-2 resolvable).
	if _, err := deployment.LoadRegistry(filepath.Join(dir, "anchors.json")); err != nil {
		t.Fatal(err)
	}
	evs, _ := root.ReadEvents(prov.TaskID)
	var sealed, egressing, egressAck, bound, completed bool
	var boundSeq int64
	for _, e := range evs {
		switch e.Class {
		case state.EvL5Transition:
			var b struct{ To, Reason string }
			_ = json.Unmarshal(e.Body, &b)
			if b.To == "SEALED" && b.Reason == "task-complete" {
				sealed = true
			}
			if b.To == "EGRESSING" {
				egressing = true
			}
		case state.EvL5Op:
			if strings.Contains(string(e.Body), `"op":"egress"`) && strings.Contains(string(e.Body), `"acknowledged"`) {
				egressAck = true
			}
		case state.EvArtifact:
			bound, boundSeq = true, e.Seq
		case state.EvLifecycle:
			if strings.Contains(string(e.Body), `"COMPLETED"`) {
				completed = true
			}
		}
	}
	if !(sealed && egressing && egressAck && bound && completed) || boundSeq != prov.ArtifactBoundSeq {
		t.Fatalf("five-link chain incomplete: sealed=%v egressing=%v egressAck=%v bound=%v completed=%v seq=%d/%d", sealed, egressing, egressAck, bound, completed, boundSeq, prov.ArtifactBoundSeq)
	}
}
